### ISSUE TITLE
How to get the evaluation results on BIRD-bench?

### ISSUE THREAD

**Issue by QingyuanLi1211** [mercatorhq/dubo-sql#1]
Hello dear author:
When I use Dubo-sql v1, after running dubo_bird.py to generate predict_dev.json, how can I verify the execution accuracy (EX)? Should I run run_evaluation.sh, or should I run dubo-sql/dubo_v1/src/evaluation.py?

**Comment by DaytonThorpe** [comment]
Run `run_evaluation.sh` after un-commenting the lines to call the test you want to run. There are four tests: EX and VES with and without oracle knowledge.
